INSERT INTO tb_role (authority) VALUES ('ROLE_VISITOR');
INSERT INTO tb_role (authority) VALUES ('ROLE_MEMBER');

INSERT INTO tb_user (name, email, password) VALUES ('Ana Green', 'ana@gmail.com', '$2a$10$eACCYoNOHEqXve8aIWT8Nu3PkMXWBaOxJ9aORUYzfMQCbVBIhZ8tG');
INSERT INTO tb_user (name, email, password) VALUES ('Bob Borwn', 'bob@gmail.com', '$2a$10$eACCYoNOHEqXve8aIWT8Nu3PkMXWBaOxJ9aORUYzfMQCbVBIhZ8tG');

INSERT INTO tb_user_role (user_id, role_id) VALUES (1, 1);
INSERT INTO tb_user_role (user_id, role_id) VALUES (1, 2);
INSERT INTO tb_user_role (user_id, role_id) VALUES (2, 1);

INSERT INTO tb_genre (name) VALUES ('Terror');
INSERT INTO tb_genre (name) VALUES ('Action');
INSERT INTO tb_genre (name) VALUES ('Comedy');
INSERT INTO tb_genre (name) VALUES ('Drama');
INSERT INTO tb_genre (name) VALUES ('Fiction');
INSERT INTO tb_genre (name) VALUES ('Thriller');

INSERT INTO tb_movie (title, sub_title, year, img_uri, synopsis, genre_id) VALUES ('The Exorcist', 'Something almost beyond comprehension is happening to a girl on this street, in this house… and a man has been sent for as a last resort. This man is The Exorcist.', 1973, 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/AezAErI7zzGsgg9WHX7zp9zz8nU.jpg', '12-year-old Regan MacNeil begins to adapt an explicit new personality as strange events befall the local area of Georgetown. Her mother becomes torn between science and superstition in a desperate bid to save her daughter, and ultimately turns to her last hope: Father Damien Karras, a troubled priest who is struggling with his own faith.', 1);
INSERT INTO tb_movie (title, sub_title, year, img_uri, synopsis, genre_id) VALUES ('It Chapter Two', 'You''ll Float Again', 2019, 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/fJWe8TyNJHCybsbdinj0b562FDT.jpg', '27 years after overcoming the malevolent supernatural entity Pennywise, the former members of the Losers'' Club, who have grown up and moved away from Derry, are brought back together by a devastating phone call.', 1);
INSERT INTO tb_movie (title, sub_title, year, img_uri, synopsis, genre_id) VALUES ('Top Gun', 'Up there with the best of the best.', 1986, 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/am0wHjplG1YynuDWz2LPWx5V9kJ.jpg', 'For Lieutenant Pete ''Maverick'' Mitchell and his friend and co-pilot Nick ''Goose'' Bradshaw, being accepted into an elite training school for fighter pilots is a dream come true. But a tragedy, as well as personal demons, will threaten Pete''s dreams of becoming an ace pilot.', 2);
INSERT INTO tb_movie (title, sub_title, year, img_uri, synopsis, genre_id) VALUES ('Rambo III', 'The first was for himself. The second for his country. This time it''s to save his friend.', 1988, 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/fOijh7CQ76EJUbPSPOyLXxgIcv7.jpg', 'Combat has taken its toll on Rambo, but he''s finally begun to find inner peace in a monastery. When Rambo''s friend and mentor Col. Trautman asks for his help on a top secret mission to Afghanistan, Rambo declines but must reconsider when Trautman is captured.', 2);
INSERT INTO tb_movie (title, sub_title, year, img_uri, synopsis, genre_id) VALUES ('Ted', 'Ted is coming', 2012, 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/cfBHNVv9pto26a4qnwJ5F0gq9jg.jpg', 'John Bennett, a man whose childhood wish of bringing his teddy bear to life came true, now must decide between keeping the relationship with the bear or his girlfriend, Lori.', 3);
INSERT INTO tb_movie (title, sub_title, year, img_uri, synopsis, genre_id) VALUES ('Click', 'What If You Had A Remote... That Controlled Your Universe?', 2006, 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/dogPJscbGwVMIWogZ8OVE0PQ05U.jpg', 'A married workaholic, Michael Newman doesn''t have time for his wife and children, not if he''s to impress his ungrateful boss and earn a well-deserved promotion. So when he meets Morty, a loopy sales clerk, he gets the answer to his prayers: a magical remote that allows him to bypass life''s little distractions with increasingly hysterical results.', 3);
INSERT INTO tb_movie (title, sub_title, year, img_uri, synopsis, genre_id) VALUES ('The Shack', 'You''re never as alone as you think.', 2017, 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/yum211HuasjazYsTabZPTNSHc1a.jpg', 'After suffering a family tragedy, Mack Phillips spirals into a deep depression causing him to question his innermost beliefs. Facing a crisis of faith, he receives a mysterious letter urging him to an abandoned shack deep in the Oregon wilderness. Despite his doubts, Mack journeys to the shack and encounters an enigmatic trio of strangers led by a woman named Papa. Through this meeting, Mack finds important truths that will transform his understanding of his tragedy and change his life forever.', 4);
INSERT INTO tb_movie (title, sub_title, year, img_uri, synopsis, genre_id) VALUES ('Hillbilly Elegy', 'Inspired by a true story three generations in the making.', 2020, 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/4Swxt0Q9KEi0WiWEDpDK1MdiDOJ.jpg', 'An urgent phone call pulls a Yale Law student back to his Ohio hometown, where he reflects on three generations of family history and his own future.', 4);
INSERT INTO tb_movie (title, sub_title, year, img_uri, synopsis, genre_id) VALUES ('Star Wars: The Rise of Skywalker', 'Every generation has a legend', 2019, 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/8ROVXHf6rtWRPiWNqI9GXWy0Rxv.jpg', 'The surviving Resistance faces the First Order once again as the journey of Rey, Finn and Poe Dameron continues. With the power and knowledge of generations behind them, the final battle begins.', 5);
INSERT INTO tb_movie (title, sub_title, year, img_uri, synopsis, genre_id) VALUES ('Harry Potter and the Order of the Phoenix', 'Evil Must Be Confronted.', 2007, 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/7qKWTyYvkyIrWgkUOHiNxHv3FNK.jpg', 'Returning for his fifth year of study at Hogwarts, Harry is stunned to find that his warnings about the return of Lord Voldemort have been ignored. Left with no choice, Harry takes matters into his own hands, training a small group of students – dubbed ''Dumbledore''s Army'' – to defend themselves against the dark arts.', 5);
INSERT INTO tb_movie (title, sub_title, year, img_uri, synopsis, genre_id) VALUES ('Zodiac', 'There''s more than one way to lose your life to a killer.', 2007, 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/jP2htGBHE7vKq4MLeC75UeC0sZH.jpg', 'The true story of the investigation of the "Zodiac Killer", a serial killer who terrified the San Francisco Bay Area, taunting police with his ciphers and letters. The case becomes an obsession for three men as their lives and careers are built and destroyed by the endless trail of clues.', 6);
INSERT INTO tb_movie (title, sub_title, year, img_uri, synopsis, genre_id) VALUES ('House at the End of the Street', 'Fear reaches out... for the girl next door.', 2012, 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/gPE36ptyUFP4IqgRDaj2mdcfju2.jpg', 'A mother and daughter move to a new town and find themselves living next door to a house where a young girl murdered her parents. When the daughter befriends the surviving son, she learns the story is far from over.', 6);

